### ISSUE TITLE
builtins.OSError: [Errno 95] fallocate with fresh container

### ISSUE THREAD

**Issue by styygeli** [graphite-project/docker-graphite-statsd#78] opened 2019-01-06 13:57 UTC
Got this error today when trying this container, fresh, no volumes defined, ZFS as backing storage for docker. I remember getting this same years and years ago with my own install in a corporate setting (no docker) when the docker user wasn't able to write to the storage folder.

```
Jan 06 15:50:54 lanfear docker[25322]: Traceback (most recent call last):
Jan 06 15:50:54 lanfear docker[25322]:   File "/opt/graphite/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
Jan 06 15:50:54 lanfear docker[25322]:     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
Jan 06 15:50:54 lanfear docker[25322]:   File "/opt/graphite/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
Jan 06 15:50:54 lanfear docker[25322]:     return self.currentContext().callWithContext(ctx, func, *args, **kw)
Jan 06 15:50:54 lanfear docker[25322]:   File "/opt/graphite/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
Jan 06 15:50:54 lanfear docker[25322]:     return func(*args,**kw)
Jan 06 15:50:54 lanfear docker[25322]:   File "/opt/graphite/lib/carbon/writer.py", line 189, in writeForever
Jan 06 15:50:54 lanfear docker[25322]:     writeCachedDataPoints()
Jan 06 15:50:54 lanfear docker[25322]: --- <exception caught here> ---
Jan 06 15:50:54 lanfear docker[25322]:   File "/opt/graphite/lib/carbon/writer.py", line 142, in writeCachedDataPoints
Jan 06 15:50:54 lanfear docker[25322]:     state.database.create(metric, archiveConfig, xFilesFactor, aggregationMethod)
Jan 06 15:50:54 lanfear docker[25322]:   File "/opt/graphite/lib/carbon/database.py", line 145, in create
Jan 06 15:50:54 lanfear docker[25322]:     self.sparse_create, self.fallocate_create)
Jan 06 15:50:54 lanfear docker[25322]:   File "/opt/graphite/lib/python3.6/site-packages/whisper.py", line 528, in create
Jan 06 15:50:54 lanfear docker[25322]:     fallocate(fh, headerSize, remaining)
Jan 06 15:50:54 lanfear docker[25322]:   File "/opt/graphite/lib/python3.6/site-packages/whisper.py", line 93, in _py_fallocate
Jan 06 15:50:54 lanfear docker[25322]:     raise IOError(res, 'fallocate')
Jan 06 15:50:54 lanfear docker[25322]: builtins.OSError: [Errno 95] fallocate
Jan 06 15:50:54 lanfear docker[25322]: 06/01/2019 06:50:54 :: [console] Error creating stats.statsd.graphiteStats.flush_time: [Errno 95] fallocate
Jan 06 15:50:54 lanfear docker[25322]: 06/01/2019 06:50:54 :: [console] Unhandled Error
```

Running this as
```
/usr/bin/docker run --name graphite -p 8080:80 -p 2003:2003 graphiteapp/docker-graphite-statsd
```

I did a peek inside the actual container and looks like it's running as root inside, and folders do exists inside. Bit stumped why it wouldn't be able to create the .wsp files. It can create the folders in the storage/

**Comment by piotr1212** [comment] 2019-01-06 16:39
Does ZFS even support fallocate? Could you try: WHISPER_FALLOCATE_CREATE = False in carbon.conf.

**Comment by deniszh** [comment] 2019-01-06 16:48
Looks like still not - https://github.com/zfsonlinux/zfs/issues/326

**Comment by styygeli** [comment] 2019-01-07 01:51
Ah interesting, didn't think of the fallocate wouldn't be faked on the ZFS.

I'll give the whisper option a try probably this evening and report back, thanks a lot :)

**Comment by piotr1212** [comment] 2019-01-07 08:10
@styygeli Are you using fuse-zfs or zfsonlinux?

**Comment by styygeli** [comment] 2019-01-07 08:57
@piotr1212 zfsonlinux on ubuntu 16.04

**Comment by piotr1212** [comment] 2019-01-07 09:46
I cannot reproduce this on Fedora 29. Maybe because it is newer?

Anyway, `[Errno 95]` is `#define EOPNOTSUPP  95  /* Operation not supported on transport endpoint */ `

>        EOPNOTSUPP
>              The filesystem containing the file referred to by fd does not
>              support this operation; or the mode is not supported by the
>              filesystem containing the file referred to by fd.

We could catch that and disable fallocate. Not sure if that should be done in whisper or in carbon.

**Comment by deniszh** [comment] 2019-01-07 11:39
I think, single fallocate call which we use is https://github.com/graphite-project/whisper/blob/master/whisper.py#L528
IMO process exception and fallback to normal creation will be enough.

**Comment by piotr1212** [comment] 2019-01-07 21:46
Seems to be a duplicate of https://github.com/graphite-project/whisper/issues/79

**Comment by styygeli** [comment] 2019-01-08 05:34
Tried today with `carbon.conf:WHISPER_FALLOCATE_CREATE = False` and container started just fine and wsp files are filling up properly. Thanks a lot :)

**Comment by deniszh** [comment] 2019-01-16 11:24
Not sure should we treat it as a bug. We have `WHISPER_FALLOCATE_CREATE = False` for exactly that purpose. Closing that for now.

**Closed by deniszh** 2019-01-16 11:24 UTC

**Comment by trinitronx** [comment] 2019-06-23 06:40
:+1:

```
WHISPER_FALLOCATE_CREATE = False
```

Resolves the issue on NFS backed by XFS also
