### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ebryerwork** [graphite-project/docker-graphite-statsd#222] opened 2023-09-11 16:06 UTC
**Please open bug only for Docker component here, if you want to do so for Graphite, please use [graphite-web repo](https://github.com/graphite-project/graphite-web/issues/new/choose)**

**Describe the bug**
Passing to the container the environment variable DEFAULT_CACHE_DURATION causes the web interface to issue an error:
502 Bad Gateway
nginx/1.20.2

**To Reproduce**
Start the container rootless with 
```
podman run --detach -e DEFAULT_CACHE_DURATION=60 --publish=4000:80 --name=graphite docker.io/graphiteapp/graphite-statsd:latest
```

Refresh the web interface. While all this is being done, have in local_settings.py DEFAULT_CACHE_DURATION either set or unset; it appears to make no difference.

**Expected behavior**
I expected the web interface to appear as usual.

**Environment (please complete the following information):**
 - OS flavor: RHEL 8.7
 - Image version: 1.1.10-5
 - Custom volumes mounted: --volume=/storage/icds/data/testgraphite/conf:/opt/graphite/conf  --volume=/storage/icds/data/testgraphite/storage:/opt/graphite/storage  --volume=/storage/icds/data/testgraphite/logs:/var/log

**Additional context**
nginx/error.log has a few entries like:

2023/09/11 15:56:52 [error] 190#190: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.100, server: , request: "GET /?width=586&height=308&target=foo.jimmy HTTP/1.1", upstream: "http://127.0.0.1:8080/?width=586&height=308&target=foo.jimmy", host: "testgraphite:4000"

corresponding to entries in access.log like:

10.0.2.100 - - [11/Sep/2023:15:56:52 +0000] "GET /?width=586&height=308&target=foo.jimmy HTTP/1.1" 502 559 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36"

before I shut down the container.

The command I gave in the earliest section of this bug report is a minimum example. The command I am using in practice is:
```
podman run  --detach  -e CARBON_AGGREGATOR_DISABLED=1  -e STATSD_DISABLED=1  -e RELAY=1  -e GRAPHITE_CARBONLINK_HOSTS="127.0.0.1:2104:1, 127.0.0.1:2204:2, 127.0.0.1:2304:3, 127.0.0.1:2404:4, 127.0.0.1:2504:5, 127.0.0.1:2604:6, 127.0.0.1:2704:7, 127.0.0.1:2804:8"  -e GRAPHITE_WSGI_PROCESSES=8  -e GRAPHITE_WSGI_THREADS=12  -e GRAPHITE_WSGI_REQUEST_TIMEOUT=600  -e DEFAULT_CACHE_DURATION=1200  --publish=4000:80  --publish=2003-2004:2003-2004  --restart=always  --volume=/storage/icds/data/testgraphite/conf:/opt/graphite/conf  --volume=/storage/icds/data/testgraphite/storage:/opt/graphite/storage  --volume=/storage/icds/data/testgraphite/logs:/var/log --name=graphite  docker.io/graphiteapp/graphite-statsd:1.1.10-5
```

I am trying to increase the timeout of the cache from 60 to 1200. I am able to make this change in the configuration file and successfully start the container; _however_, I do not know if it is respected by the the container. For example, GRAPHITE_CARBONLINK_HOSTS is _not_ respected by the container if set only in the config file.

I have tried having in local_settings.py DEFAULT_CACHE_DURATION set or unset while I tried passing DEFAULT_CACHE_DURATION as an environment variable; it appears to make no difference. It always causes an nginx "bad gateway" error when I pass the environment variable.

Will the container respect DEFAULT_CACHE_DURATION if it's set only in local_settings.py? Or is it like GRAPHITE_CARBONLINK_HOSTS and needs to be set both in the config file and using an environment variable to actually take effect?

**Comment by deniszh** [comment] 2023-09-12 10:02
Please do not use `DEFAULT_CACHE_DURATION`, use either `GRAPHITE_DEFAULT_CACHE_DURATION` or `CACHE_DURATION`, as documented.

**Comment by deniszh** [comment] 2023-09-12 10:07
Or you can use DEFAULT_CACHE_DURATION=60 and CACHE_DURATION=1200 (only together) but that makes little sense.  That's coming out of 
```python
if (os.getenv("DEFAULT_CACHE_DURATION") is not None):
    DEFAULT_CACHE_DURATION = int(os.getenv("CACHE_DURATION"))
```
theoretically that's not needed and can be removed.

**Comment by deniszh** [comment] 2023-09-12 10:33
Should be fixed in master, but in your case just use GRAPHITE_DEFAULT_CACHE_DURATION=1200 instead.

**Comment by ebryerwork** [comment] 2023-09-13 15:32
I see I got DEFAULT_CACHE_DURATION and GRAPHITE_DEFAULT_CACHE_DURATION mixed. Thanks. I'm still having difficulty though....

If I run:
```
podman run --detach --env=GRAPHITE_DEFAULT_CACHE_DURATION=60 --publish=4000:80  --publish=2003-2004:2003-2004 --name=graphite docker.io/graphiteapp/graphite-statsd:1.1.10-5
```
Then this query fails with a 502 error:
```
wget 'http://testgraphite.test.hpc.psu.edu:4000/render?target=aliasByNode(carbon.agents.creates,%201)&format=raw&from=-2h&until=-1min'
```
And I get in nginx/error.log:

2023/09/13 15:22:30 [error] 72#72: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.2.100, server: , request: "GET /render?target=aliasByNode(carbon.agents.creates,%201)&format=raw&from=-2h&until=-1min HTTP/1.1", upstream: "http://127.0.0.1:8080/render?target=aliasByNode(carbon.agents.creates,%201)&format=raw&from=-2h&until=-1min", host: "testgraphite.test.hpc.psu.edu:4000"

I do not get such an error, and the wget query works, if `--env=GRAPHITE_DEFAULT_CACHE_DURATION=60` is not specified.

**Comment by deniszh** [comment] 2023-09-14 08:12
Hi @ebryerwork,
Sorry, can't reproduce.
Tried both
```
docker run  -p 80:80 -e GRAPHITE_DEFAULT_CACHE_DURATION=1200 \
 -p 2003-2004:2003-2004\
 -p 2023-2024:2023-2024\
 -p 8125:8125/udp\
 -p 8126:8126 \
 graphiteapp/graphite-statsd:1.1.10-5
```
and
```
docker run  -p 80:80 -e GRAPHITE_DEFAULT_CACHE_DURATION=1200 \
 -p 2003-2004:2003-2004\
 -p 2023-2024:2023-2024\
 -p 8125:8125/udp\
 -p 8126:8126 \
 graphiteapp/graphite-statsd:latest
```
- both works fine.

**Comment by ebryerwork** [comment] 2023-09-18 20:40
I wasn't able to reproduce it either, so I was doing something odd on that system at that day and time. Thanks very much.

**Closed** 2023-09-18 20:40 UTC
Labels: bug
